default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: lokesh@123
  host: localhost
  port: 5432

development:
  <<: *default
  database: saas_development

test:
  <<: *default
  database: saas_test

production:
  <<: *default
  database: saas_production
